services:
  - type: web
    name: leadhunterai-backend-3
    runtime: python
    env: python
    region: oregon
    plan: free  # Free tier works
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11