services:
  - type: web
    name: leadhunterai-backend-3-432s
    plan: free
    env: python
    buildCommand: pip install fastapi uvicorn requests python-dotenv praw
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
